[tool.poetry]
name = "tdd"
version = "0.1.0"
description = "tdd exercise"
authors = ["yo-aka-gene <yujiokano@keio.jp>"]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
